### ISSUE TITLE
we need to decide a regular meeting time

### ISSUE THREAD

**Issue by cbm755** [ubcs3/2018-Winter-OSS#3]

**Comment by circularpenguin** [comment]
I can't do Mondays 1:30-2:30, Tuesdays 11-12 & after 5, and Thursdays 4-5 (but this is flexible!)

**Comment by patrickwalls** [comment]
How about Tuesday 4-5? @cbm755 are there other times that work with your schedule?

**Comment by circularpenguin** [comment]
That's good for me!

**Comment by patrickwalls** [comment]
Let's do it. Tuesday 4-5pm.

**Comment by cbm755** [comment]
sorry, I can't generally make 4-5pm Tues.  I could do:
Tues: 5pm--6pm, but not ideal.
Wed: 4pm--6pm
Thurs: 4pm--6pm
Friday: 3pm--6pm
(this term is a bit of a special case, I'm not usually this inflexible).

**Comment by patrickwalls** [comment]
Let's go with Thursday 4-5. Sorry for all the changes! 😃
